version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - add_ssh_keys:
          fingerprints:
            - "54:7e:55:49:d3:5b:67:d6:12:d0:a0:51:ed:d7:81:8c"
      - checkout
      - run: make check-has-release
      - run: make install-deploy-deps
      - run: make prepare-release
      - run: poetry build
      - run: make publish-changes
      - run: make create-github-release
      - run: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD

workflows:
  Deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
